/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ABC_aplicacion;

import java.awt.Color;

/**
 *
 * @author Jaasiel
 */
public class pagina_principal extends javax.swing.JFrame {

    /**
     * Creates new form pagina_principal
     */
    
    public pagina_principal() {
        initComponents();
        setLocationRelativeTo(null);
        
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        resultado1 = new javax.swing.JLabel();
        binario6 = new javax.swing.JToggleButton();
        binario5 = new javax.swing.JToggleButton();
        binario4 = new javax.swing.JToggleButton();
        binario3 = new javax.swing.JToggleButton();
        binario2 = new javax.swing.JToggleButton();
        binario1 = new javax.swing.JToggleButton();
        decimal6 = new javax.swing.JToggleButton();
        decimal5 = new javax.swing.JToggleButton();
        decimal4 = new javax.swing.JToggleButton();
        decimal3 = new javax.swing.JToggleButton();
        decimal2 = new javax.swing.JToggleButton();
        decimal1 = new javax.swing.JToggleButton();
        binarioResultado = new javax.swing.JLabel();
        sistemaBinario = new javax.swing.JLabel();
        binarioDisplay2 = new javax.swing.JLabel();
        binarioDisplay1 = new javax.swing.JLabel();
        sistemaBinario1 = new javax.swing.JLabel();
        boton_regresar_tabla = new javax.swing.JLabel();
        numero_suma4 = new javax.swing.JLabel();
        numero_suma3 = new javax.swing.JLabel();
        numero_suma2 = new javax.swing.JLabel();
        numero_suma1 = new javax.swing.JLabel();
        simboloSuma1 = new javax.swing.JLabel();
        simboloSuma2 = new javax.swing.JLabel();
        simboloIgual = new javax.swing.JLabel();
        simboloSuma3 = new javax.swing.JLabel();
        numero_suma5 = new javax.swing.JLabel();
        numero_suma6 = new javax.swing.JLabel();
        simboloSuma4 = new javax.swing.JLabel();
        simboloSuma5 = new javax.swing.JLabel();
        suma_barra = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();
        pagina_principal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resultado1.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 40)); // NOI18N
        resultado1.setForeground(new java.awt.Color(255, 153, 51));
        resultado1.setText("63");
        jPanel1.add(resultado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 160, 50, 60));

        binario6.setBackground(new java.awt.Color(0, 160, 226));
        binario6.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 48)); // NOI18N
        binario6.setForeground(new java.awt.Color(255, 255, 255));
        binario6.setText("1");
        binario6.setToolTipText("");
        binario6.setBorder(null);
        binario6.setBorderPainted(false);
        binario6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        binario6.setFocusPainted(false);
        binario6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binario6ActionPerformed(evt);
            }
        });
        jPanel1.add(binario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 159, 87));

        binario5.setBackground(new java.awt.Color(0, 160, 226));
        binario5.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 48)); // NOI18N
        binario5.setForeground(new java.awt.Color(255, 255, 255));
        binario5.setText("1");
        binario5.setBorder(null);
        binario5.setBorderPainted(false);
        binario5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        binario5.setFocusPainted(false);
        binario5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binario5ActionPerformed(evt);
            }
        });
        jPanel1.add(binario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 159, 87));

        binario4.setBackground(new java.awt.Color(0, 160, 226));
        binario4.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 48)); // NOI18N
        binario4.setForeground(new java.awt.Color(255, 255, 255));
        binario4.setText("1");
        binario4.setBorder(null);
        binario4.setBorderPainted(false);
        binario4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        binario4.setFocusPainted(false);
        binario4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binario4ActionPerformed(evt);
            }
        });
        jPanel1.add(binario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 159, 87));

        binario3.setBackground(new java.awt.Color(0, 160, 226));
        binario3.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 48)); // NOI18N
        binario3.setForeground(new java.awt.Color(255, 255, 255));
        binario3.setText("1");
        binario3.setToolTipText("");
        binario3.setBorder(null);
        binario3.setFocusPainted(false);
        binario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binario3ActionPerformed(evt);
            }
        });
        jPanel1.add(binario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 159, 87));

        binario2.setBackground(new java.awt.Color(0, 160, 226));
        binario2.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 48)); // NOI18N
        binario2.setForeground(new java.awt.Color(255, 255, 255));
        binario2.setText("1");
        binario2.setBorder(null);
        binario2.setFocusPainted(false);
        binario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binario2ActionPerformed(evt);
            }
        });
        jPanel1.add(binario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 159, 87));

        binario1.setBackground(new java.awt.Color(0, 160, 226));
        binario1.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 48)); // NOI18N
        binario1.setForeground(new java.awt.Color(255, 255, 255));
        binario1.setText("1");
        binario1.setBorder(null);
        binario1.setFocusPainted(false);
        binario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binario1ActionPerformed(evt);
            }
        });
        jPanel1.add(binario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 159, 87));

        decimal6.setBackground(new java.awt.Color(193, 121, 238));
        decimal6.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 48)); // NOI18N
        decimal6.setForeground(new java.awt.Color(255, 255, 255));
        decimal6.setText("32\n");
        decimal6.setToolTipText("");
        decimal6.setBorder(null);
        decimal6.setFocusPainted(false);
        jPanel1.add(decimal6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 159, 87));

        decimal5.setBackground(new java.awt.Color(193, 121, 238));
        decimal5.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 48)); // NOI18N
        decimal5.setForeground(new java.awt.Color(255, 255, 255));
        decimal5.setText("16\n");
        decimal5.setBorder(null);
        decimal5.setBorderPainted(false);
        decimal5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        decimal5.setFocusPainted(false);
        jPanel1.add(decimal5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 159, 87));

        decimal4.setBackground(new java.awt.Color(193, 121, 238));
        decimal4.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 48)); // NOI18N
        decimal4.setForeground(new java.awt.Color(255, 255, 255));
        decimal4.setText("8");
        decimal4.setBorder(null);
        decimal4.setBorderPainted(false);
        decimal4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        decimal4.setFocusPainted(false);
        jPanel1.add(decimal4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 159, 87));

        decimal3.setBackground(new java.awt.Color(193, 121, 238));
        decimal3.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 48)); // NOI18N
        decimal3.setForeground(new java.awt.Color(255, 255, 255));
        decimal3.setText("4");
        decimal3.setToolTipText("");
        decimal3.setBorder(null);
        decimal3.setFocusPainted(false);
        jPanel1.add(decimal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 159, 87));

        decimal2.setBackground(new java.awt.Color(193, 121, 238));
        decimal2.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 48)); // NOI18N
        decimal2.setForeground(new java.awt.Color(255, 255, 255));
        decimal2.setText("2");
        decimal2.setBorder(null);
        decimal2.setFocusPainted(false);
        jPanel1.add(decimal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 159, 87));

        decimal1.setBackground(new java.awt.Color(193, 121, 238));
        decimal1.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 48)); // NOI18N
        decimal1.setForeground(new java.awt.Color(255, 255, 255));
        decimal1.setText("1");
        decimal1.setBorder(null);
        decimal1.setFocusPainted(false);
        jPanel1.add(decimal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 120, 159, 87));

        binarioResultado.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 36)); // NOI18N
        binarioResultado.setForeground(new java.awt.Color(255, 153, 51));
        binarioResultado.setText("111111");
        jPanel1.add(binarioResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 50, 180, 50));

        sistemaBinario.setBackground(new java.awt.Color(255, 255, 255));
        sistemaBinario.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 24)); // NOI18N
        sistemaBinario.setForeground(new java.awt.Color(146, 147, 225));
        sistemaBinario.setText("Sistema Decimal");
        jPanel1.add(sistemaBinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 120, -1, -1));

        binarioDisplay2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abc/folder_imagenes/binarioFondo.png"))); // NOI18N
        jPanel1.add(binarioDisplay2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 140, 170, 70));

        binarioDisplay1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abc/folder_imagenes/binarioFondo.png"))); // NOI18N
        jPanel1.add(binarioDisplay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 40, 160, 60));

        sistemaBinario1.setBackground(new java.awt.Color(255, 255, 255));
        sistemaBinario1.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 24)); // NOI18N
        sistemaBinario1.setForeground(new java.awt.Color(146, 147, 225));
        sistemaBinario1.setText("Sistema Binario");
        jPanel1.add(sistemaBinario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 1270, 220));

        boton_regresar_tabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abc/folder_imagenes/boton_regresar_tabla.png"))); // NOI18N
        boton_regresar_tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_regresar_tablaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_regresar_tablaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_regresar_tablaMouseExited(evt);
            }
        });
        getContentPane().add(boton_regresar_tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 180, 60));

        numero_suma4.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 36)); // NOI18N
        numero_suma4.setForeground(new java.awt.Color(114, 113, 115));
        numero_suma4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero_suma4.setText("8");
        getContentPane().add(numero_suma4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 560, 70, 120));

        numero_suma3.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 36)); // NOI18N
        numero_suma3.setForeground(new java.awt.Color(114, 113, 115));
        numero_suma3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero_suma3.setText("4");
        getContentPane().add(numero_suma3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 560, 70, 120));

        numero_suma2.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 36)); // NOI18N
        numero_suma2.setForeground(new java.awt.Color(114, 113, 115));
        numero_suma2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero_suma2.setText("2");
        getContentPane().add(numero_suma2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 560, 70, 120));

        numero_suma1.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 36)); // NOI18N
        numero_suma1.setForeground(new java.awt.Color(114, 113, 115));
        numero_suma1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero_suma1.setText("1");
        getContentPane().add(numero_suma1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 560, 70, 120));

        simboloSuma1.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 36)); // NOI18N
        simboloSuma1.setForeground(new java.awt.Color(114, 113, 115));
        simboloSuma1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        simboloSuma1.setText("+");
        getContentPane().add(simboloSuma1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 590, 40, 60));

        simboloSuma2.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 36)); // NOI18N
        simboloSuma2.setForeground(new java.awt.Color(114, 113, 115));
        simboloSuma2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        simboloSuma2.setText("+");
        getContentPane().add(simboloSuma2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 590, 40, 60));

        simboloIgual.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 36)); // NOI18N
        simboloIgual.setForeground(new java.awt.Color(114, 113, 115));
        simboloIgual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        simboloIgual.setText("=");
        getContentPane().add(simboloIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 590, 40, 60));

        simboloSuma3.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 36)); // NOI18N
        simboloSuma3.setForeground(new java.awt.Color(114, 113, 115));
        simboloSuma3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        simboloSuma3.setText("+");
        getContentPane().add(simboloSuma3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 590, 40, 60));

        numero_suma5.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 36)); // NOI18N
        numero_suma5.setForeground(new java.awt.Color(114, 113, 115));
        numero_suma5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero_suma5.setText("16");
        getContentPane().add(numero_suma5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, 70, 120));

        numero_suma6.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 36)); // NOI18N
        numero_suma6.setForeground(new java.awt.Color(114, 113, 115));
        numero_suma6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero_suma6.setText("32");
        getContentPane().add(numero_suma6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, 70, 120));

        simboloSuma4.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 36)); // NOI18N
        simboloSuma4.setForeground(new java.awt.Color(114, 113, 115));
        simboloSuma4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        simboloSuma4.setText("+");
        getContentPane().add(simboloSuma4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 590, 40, 60));

        simboloSuma5.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 36)); // NOI18N
        simboloSuma5.setForeground(new java.awt.Color(114, 113, 115));
        simboloSuma5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        simboloSuma5.setText("+");
        getContentPane().add(simboloSuma5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 590, 40, 60));

        suma_barra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abc/folder_imagenes/barra_suma.png"))); // NOI18N
        suma_barra.setText("jLabel1");
        getContentPane().add(suma_barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 970, 90));

        resultado.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 48)); // NOI18N
        resultado.setForeground(new java.awt.Color(255, 51, 51));
        resultado.setText("63");
        getContentPane().add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 590, 100, 60));

        pagina_principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abc/folder_imagenes/abc PAGINA_PRINCIPAL.png"))); // NOI18N
        pagina_principal.setText(" ");
        getContentPane().add(pagina_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public int total6=32,total5=16, total4=8,total3=4,total2=2,total1=1,total;
public String[] binario_array={"1","1","1","1","1","1"};


    private void binario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binario1ActionPerformed
       
        if(binario1.isSelected()){
            binario1.setText("0");
            numero_suma1.setText("0");
            total1=0;
            total=total2+total3+total4+total5+total6;
            resultado.setText(String.valueOf(total));
            resultado1.setText(String.valueOf(total));
            binario_array[0]="0";
           binarioResultado.setText(binario_array[5]+binario_array[4]+binario_array[3]+binario_array[2]+binario_array[1]+binario_array[0]); 
        }else{
            binario1.setBackground(new Color(0,160,226));
            binario1.setText("1");
            numero_suma1.setText("1");
            total1=1;
             total=total1+total2+total3+total4+total5+total6;
            resultado.setText(String.valueOf(total));
            resultado1.setText(String.valueOf(total));
           binario_array[0]="1";
          binarioResultado.setText(binario_array[5]+binario_array[4]+binario_array[3]+binario_array[2]+binario_array[1]+binario_array[0]); 

        }
    }//GEN-LAST:event_binario1ActionPerformed

    private void binario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binario2ActionPerformed
        if(binario2.isSelected()){
            binario2.setText("0");
            numero_suma2.setText("0");
            total2=0;
            total=total1+total3+total4+total5+total6;
            resultado.setText(String.valueOf(total));
            resultado1.setText(String.valueOf(total));
            binario_array[1]="0";
            binarioResultado.setText(binario_array[5]+binario_array[4]+binario_array[3]+binario_array[2]+binario_array[1]+binario_array[0]); 

        }else{
            binario2.setBackground(new Color(0,160,226));
            binario2.setText("1");
            numero_suma2.setText("2");
            total2=2;
             total=total1+total2+total3+total4+total5+total6;
            resultado.setText(String.valueOf(total));
            resultado1.setText(String.valueOf(total));
            binario_array[1]="1";
            binarioResultado.setText(binario_array[5]+binario_array[4]+binario_array[3]+binario_array[2]+binario_array[1]+binario_array[0]); 

        }
    }//GEN-LAST:event_binario2ActionPerformed

    private void binario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binario3ActionPerformed
        if(binario3.isSelected()){
             binario3.setText("0");
            numero_suma3.setText("0");
            total3=0;
            total=total1+total2+total4+total5+total6;
            resultado.setText(String.valueOf(total));
            resultado1.setText(String.valueOf(total));
            binario_array[2]="0";
             binarioResultado.setText(binario_array[5]+binario_array[4]+binario_array[3]+binario_array[2]+binario_array[1]+binario_array[0]); 

        }else{
            binario3.setBackground(new Color(0,160,226));
            binario3.setText("1");
            numero_suma3.setText("4");
            total3=4;
            total=total1+total2+total3+total4+total5+total6;
            resultado.setText(String.valueOf(total));
            resultado1.setText(String.valueOf(total));
            binario_array[2]="1";
            binarioResultado.setText(binario_array[5]+binario_array[4]+binario_array[3]+binario_array[2]+binario_array[1]+binario_array[0]); 
        }
    }//GEN-LAST:event_binario3ActionPerformed

    private void binario4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binario4ActionPerformed
        // TODO add your handling code here:
        if(binario4.isSelected()){
            binario4.setText("0");
            numero_suma4.setText("0");
            total4=0;
            total=total1+total2+total3+total5+total6;
           resultado.setText(String.valueOf(total));
           resultado1.setText(String.valueOf(total));
           binario_array[3]="0";
           binarioResultado.setText(binario_array[5]+binario_array[4]+binario_array[3]+binario_array[2]+binario_array[1]+binario_array[0]); 

        }else{
            binario4.setBackground(new Color(0,160,226));
            binario4.setText("1");
            numero_suma4.setText("8");
            total4=8;
             total=total1+total2+total3+total4+total5+total6;
            resultado.setText(String.valueOf(total));
            resultado1.setText(String.valueOf(total));
            binario_array[3]="1";
             binarioResultado.setText(binario_array[5]+binario_array[4]+binario_array[3]+binario_array[2]+binario_array[1]+binario_array[0]); 
        }
    }//GEN-LAST:event_binario4ActionPerformed

    private void binario5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binario5ActionPerformed
        // TODO add your handling code here:
        if(binario5.isSelected()){
            binario5.setText("0");
            numero_suma5.setText("0");
            total5=0;
            total=total1+total2+total3+total4+total6;
            resultado.setText(String.valueOf(total));
            resultado1.setText(String.valueOf(total));
            binario_array[4]="0";
           binarioResultado.setText(binario_array[5]+binario_array[4]+binario_array[3]+binario_array[2]+binario_array[1]+binario_array[0]); 
        }else{
            binario5.setBackground(new Color(0,160,226));
            binario5.setText("1");
            numero_suma5.setText("16");
            total5=16;
             total=total1+total2+total3+total4+total5+total6;
            resultado.setText(String.valueOf(total));
            resultado1.setText(String.valueOf(total));
             binario_array[4]="1";
           binarioResultado.setText(binario_array[5]+binario_array[4]+binario_array[3]+binario_array[2]+binario_array[1]+binario_array[0]); 
        }
    }//GEN-LAST:event_binario5ActionPerformed

    private void binario6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binario6ActionPerformed
        // TODO add your handling code here:
                                       
        // TODO add your handling code here:
        if(binario6.isSelected()){
            binario6.setText("0");
            numero_suma6.setText("0");
            total6=0;
            total=total1+total2+total3+total4+total5;
            resultado.setText(String.valueOf(total));
            resultado1.setText(String.valueOf(total));
            binario_array[5]="0";
            binarioResultado.setText(binario_array[5]+binario_array[4]+binario_array[3]+binario_array[2]+binario_array[1]+binario_array[0]); 
        }else{
            binario6.setBackground(new Color(0,160,226));
            binario6.setText("1");
            numero_suma6.setText("32");
            total6=32;
             total=total1+total2+total3+total4+total5+total6;
            resultado.setText(String.valueOf(total));
            resultado1.setText(String.valueOf(total));
            binario_array[5]="1";
            binarioResultado.setText(binario_array[5]+binario_array[4]+binario_array[3]+binario_array[2]+binario_array[1]+binario_array[0]); 
    }                                        

    }//GEN-LAST:event_binario6ActionPerformed

    private void boton_regresar_tablaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_regresar_tablaMouseEntered
        // TODO add your handling code here:
        boton_regresar_tabla.setBounds(25, 110, 180, 60);
    }//GEN-LAST:event_boton_regresar_tablaMouseEntered

    private void boton_regresar_tablaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_regresar_tablaMouseExited
        // TODO add your handling code here:
        boton_regresar_tabla.setBounds(30, 110, 180, 60);
    }//GEN-LAST:event_boton_regresar_tablaMouseExited

    private void boton_regresar_tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_regresar_tablaMouseClicked
        // TODO add your handling code here:
        pagina_eleccion pagina=new pagina_eleccion();
        pagina.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_regresar_tablaMouseClicked

       
    
    /**     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pagina_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pagina_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pagina_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pagina_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pagina_principal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton binario1;
    private javax.swing.JToggleButton binario2;
    private javax.swing.JToggleButton binario3;
    private javax.swing.JToggleButton binario4;
    private javax.swing.JToggleButton binario5;
    private javax.swing.JToggleButton binario6;
    private javax.swing.JLabel binarioDisplay1;
    private javax.swing.JLabel binarioDisplay2;
    private javax.swing.JLabel binarioResultado;
    private javax.swing.JLabel boton_regresar_tabla;
    private javax.swing.JToggleButton decimal1;
    private javax.swing.JToggleButton decimal2;
    private javax.swing.JToggleButton decimal3;
    private javax.swing.JToggleButton decimal4;
    private javax.swing.JToggleButton decimal5;
    private javax.swing.JToggleButton decimal6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel numero_suma1;
    private javax.swing.JLabel numero_suma2;
    private javax.swing.JLabel numero_suma3;
    private javax.swing.JLabel numero_suma4;
    private javax.swing.JLabel numero_suma5;
    private javax.swing.JLabel numero_suma6;
    private javax.swing.JLabel pagina_principal;
    private javax.swing.JLabel resultado;
    private javax.swing.JLabel resultado1;
    private javax.swing.JLabel simboloIgual;
    private javax.swing.JLabel simboloSuma1;
    private javax.swing.JLabel simboloSuma2;
    private javax.swing.JLabel simboloSuma3;
    private javax.swing.JLabel simboloSuma4;
    private javax.swing.JLabel simboloSuma5;
    private javax.swing.JLabel sistemaBinario;
    private javax.swing.JLabel sistemaBinario1;
    private javax.swing.JLabel suma_barra;
    // End of variables declaration//GEN-END:variables
}
