/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ABC_aplicacion;

/**
 *
 * @author Jaasiel
 */
public class pagina_conversor extends javax.swing.JFrame {

    /**
     * Creates new form pagina_conversor
     */
    public pagina_conversor() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        binary_kid = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        boton_regresar_conversor = new javax.swing.JLabel();
        boton_conversion = new javax.swing.JLabel();
        resultado_conversion = new javax.swing.JLabel();
        ingreso_decimal = new javax.swing.JTextField();
        baner_conversor = new javax.swing.JLabel();
        fondo_conversor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        binary_kid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abc/folder_imagenes/niño binario.jpg"))); // NOI18N
        getContentPane().add(binary_kid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 330, 570));

        jLabel1.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 153));
        jLabel1.setText("(Solo numeros enteros)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, -1, -1));

        boton_regresar_conversor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abc/folder_imagenes/boton_regresar_tabla.png"))); // NOI18N
        boton_regresar_conversor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_regresar_conversorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_regresar_conversorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_regresar_conversorMouseExited(evt);
            }
        });
        getContentPane().add(boton_regresar_conversor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 150, 60));

        boton_conversion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abc/folder_imagenes/boton_convertir.png"))); // NOI18N
        boton_conversion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_conversionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_conversionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_conversionMouseExited(evt);
            }
        });
        getContentPane().add(boton_conversion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, 410, 60));

        resultado_conversion.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 24)); // NOI18N
        resultado_conversion.setForeground(new java.awt.Color(255, 102, 102));
        resultado_conversion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(resultado_conversion, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 550, 370, 50));

        ingreso_decimal.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 30)); // NOI18N
        ingreso_decimal.setForeground(new java.awt.Color(102, 102, 102));
        ingreso_decimal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ingreso_decimal.setBorder(null);
        getContentPane().add(ingreso_decimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 380, 40));

        baner_conversor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abc/folder_imagenes/abc login baner.png"))); // NOI18N
        getContentPane().add(baner_conversor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1370, 120));

        fondo_conversor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abc/folder_imagenes/bloque_plantilla.jpg"))); // NOI18N
        getContentPane().add(fondo_conversor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_regresar_conversorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_regresar_conversorMouseClicked
        // TODO add your handling code here:
        pagina_eleccion pagina=new pagina_eleccion();
        pagina.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_regresar_conversorMouseClicked

    private void boton_regresar_conversorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_regresar_conversorMouseEntered
        // TODO add your handling code here:
        boton_regresar_conversor.setBounds(15, 120, 180, 60);
    }//GEN-LAST:event_boton_regresar_conversorMouseEntered

    private void boton_regresar_conversorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_regresar_conversorMouseExited
        // TODO add your handling code here:
         boton_regresar_conversor.setBounds(20, 120, 180, 60);
    }//GEN-LAST:event_boton_regresar_conversorMouseExited

    private void boton_conversionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_conversionMouseClicked
        // TODO add your handling code here:
        try{
            
            int numero_ingresado=Integer.parseInt(ingreso_decimal.getText()),res_modulo;
        String res_binario="";
        do{
            res_modulo=(numero_ingresado%2);
            res_binario=res_modulo+res_binario;
            numero_ingresado/=2;
            }while(numero_ingresado>0);
        resultado_conversion.setText(res_binario);
            
            
        }catch(Exception e){
           
            
            
        }
        
        
    }//GEN-LAST:event_boton_conversionMouseClicked

    private void boton_conversionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_conversionMouseEntered
        // TODO add your handling code here:
        boton_conversion.setBounds(480, 420, 408, 58);
    }//GEN-LAST:event_boton_conversionMouseEntered

    private void boton_conversionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_conversionMouseExited
        // TODO add your handling code here:
        boton_conversion.setBounds(480, 420, 410, 60);
    }//GEN-LAST:event_boton_conversionMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pagina_conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pagina_conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pagina_conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pagina_conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pagina_conversor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel baner_conversor;
    private javax.swing.JLabel binary_kid;
    private javax.swing.JLabel boton_conversion;
    private javax.swing.JLabel boton_regresar_conversor;
    private javax.swing.JLabel fondo_conversor;
    private javax.swing.JTextField ingreso_decimal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel resultado_conversion;
    // End of variables declaration//GEN-END:variables
}
