/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ABC_aplicacion;

import static ABC_aplicacion.login.nombre;
import javax.swing.JLabel;
/**
 *
 * @author Jaasiel
 */
public class pagina_eleccion extends javax.swing.JFrame {
    
    /**
     * Creates new form pagina_eleccion
     */
    public pagina_eleccion() {
        initComponents();
      nombre_pagina_eleccion.setText(nombre);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        boton_regresarEleccion = new javax.swing.JLabel();
        nombre_pagina_eleccion = new javax.swing.JLabel();
        eleccion_3 = new javax.swing.JLabel();
        eleccion_2 = new javax.swing.JLabel();
        eleccion_1 = new javax.swing.JLabel();
        gif_atomo = new javax.swing.JLabel();
        fondo_eleccion = new javax.swing.JLabel();
        fondo_ola = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_regresarEleccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abc/folder_imagenes/regresar_paginaEleccion.png"))); // NOI18N
        boton_regresarEleccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_regresarEleccionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_regresarEleccionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_regresarEleccionMouseExited(evt);
            }
        });
        jPanel1.add(boton_regresarEleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 150, 60));

        nombre_pagina_eleccion.setFont(new java.awt.Font("HelveticaNeueLT Std ExtBlk Cn", 3, 60)); // NOI18N
        nombre_pagina_eleccion.setForeground(new java.awt.Color(153, 153, 255));
        nombre_pagina_eleccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre_pagina_eleccion.setText("JAASIEL");
        jPanel1.add(nombre_pagina_eleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 1230, 80));

        eleccion_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abc/folder_imagenes/boton_eleccion3.png"))); // NOI18N
        eleccion_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eleccion_3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eleccion_3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eleccion_3MouseExited(evt);
            }
        });
        jPanel1.add(eleccion_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 580, 430, 140));

        eleccion_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abc/folder_imagenes/boton_eleccion2.png"))); // NOI18N
        eleccion_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eleccion_2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eleccion_2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eleccion_2MouseExited(evt);
            }
        });
        jPanel1.add(eleccion_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 430, 140));

        eleccion_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abc/folder_imagenes/boton_eleccion1.png"))); // NOI18N
        eleccion_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eleccion_1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eleccion_1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eleccion_1MouseExited(evt);
            }
        });
        jPanel1.add(eleccion_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 430, 140));

        gif_atomo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abc/folder_imagenes/atomo.gif"))); // NOI18N
        jPanel1.add(gif_atomo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 510, 370));

        fondo_eleccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abc/folder_imagenes/pagina_eleccion_1.png"))); // NOI18N
        fondo_eleccion.setText("jLabel1");
        jPanel1.add(fondo_eleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        fondo_ola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abc/folder_imagenes/ola_animacion.gif"))); // NOI18N
        jPanel1.add(fondo_ola, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, -10, 520, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eleccion_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eleccion_2MouseClicked
        // TODO add your handling code here:
        pagina_principal tabla=new pagina_principal();
        tabla.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_eleccion_2MouseClicked

    private void eleccion_2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eleccion_2MouseEntered
        // TODO add your handling code here:
        eleccion_2.setBounds(470, 440, 440 , 150);
    }//GEN-LAST:event_eleccion_2MouseEntered

    private void eleccion_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eleccion_2MouseExited
        // TODO add your handling code here:
         eleccion_2.setBounds(470, 440, 430 , 140);
    }//GEN-LAST:event_eleccion_2MouseExited

    private void eleccion_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eleccion_3MouseClicked
        // TODO add your handling code here:
        pagina_conversor pagina3= new pagina_conversor();
        pagina3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_eleccion_3MouseClicked

    private void eleccion_3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eleccion_3MouseEntered
        // TODO add your handling code here:
        eleccion_3.setBounds(460, 580, 440, 150);
    }//GEN-LAST:event_eleccion_3MouseEntered

    private void eleccion_3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eleccion_3MouseExited
        // TODO add your handling code here:
        eleccion_3.setBounds(460, 580, 430, 140);
    }//GEN-LAST:event_eleccion_3MouseExited

    private void eleccion_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eleccion_1MouseClicked
        // TODO add your handling code here:
        pagina_que_explica pagina1= new pagina_que_explica();
        pagina1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_eleccion_1MouseClicked

    private void eleccion_1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eleccion_1MouseEntered
        // TODO add your handling code here:
        eleccion_1.setBounds(470, 300, 440, 150);
    }//GEN-LAST:event_eleccion_1MouseEntered

    private void eleccion_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eleccion_1MouseExited
        // TODO add your handling code here:
         eleccion_1.setBounds(470, 300, 430, 140);
    }//GEN-LAST:event_eleccion_1MouseExited

    private void boton_regresarEleccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_regresarEleccionMouseClicked
        // TODO add your handling code here:
        login login1=new login();
        login1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_regresarEleccionMouseClicked

    private void boton_regresarEleccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_regresarEleccionMouseEntered
        // TODO add your handling code here:
        boton_regresarEleccion.setBounds(17, 110, 150, 60);
    }//GEN-LAST:event_boton_regresarEleccionMouseEntered

    private void boton_regresarEleccionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_regresarEleccionMouseExited
        // TODO add your handling code here:
         boton_regresarEleccion.setBounds(20, 110, 150, 60);
    }//GEN-LAST:event_boton_regresarEleccionMouseExited
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pagina_eleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pagina_eleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pagina_eleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pagina_eleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pagina_eleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel boton_regresarEleccion;
    private javax.swing.JLabel eleccion_1;
    private javax.swing.JLabel eleccion_2;
    private javax.swing.JLabel eleccion_3;
    private javax.swing.JLabel fondo_eleccion;
    private javax.swing.JLabel fondo_ola;
    private javax.swing.JLabel gif_atomo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombre_pagina_eleccion;
    // End of variables declaration//GEN-END:variables
}
